### ISSUE TITLE
"No space left on device" when creating logsearch-boshrelease

### ISSUE THREAD

**Issue by mrdavidlaing** [logsearch/workspace#8]
@dpb587 says:

>I'm having trouble working with the logsearch-boshrelease within logsearch/workspace. This is my first attempt of working within the virtual machine. I've gotten several errors related to the /tmp mount only being 120M and not sure what to do.
>
>First happened when running `bosh sync blobs` - it errored downloading one of the larger blobs with "No space left on device". I reran the command and it happened to work the next time around.
>
>Second happens when trying to create a tarball that I can upload to the local bosh-lite. Running `bosh upload release` silently fails with "Extract tarball...FAILED / Release is invalid, please fix, verify and upload again". Running `bosh create release --force --with-tarball` gives the "No space left on device" error when adding the logstash package (106 MB).
>
>To get to that point, I had done:
```
cd src/
git clone https://github.com/logsearch/logsearch-boshrelease.git
cd logsearch-boshrelease
bosh target 192.168.50.4 # admin/admin
bosh sync blobs
bosh create release --force
bosh create release --force --with-tarball
```
>fails with
```
Copying packages...
-------------------
elasticsearch               27.5M
java7                       32.9M
kibana                      622.7K
logstash                    105.9M
/usr/lib/ruby/1.9.1/fileutils.rb:1372:in `copy_stream': No space left on device - write (Errno::ENOSPC)
	from /usr/lib/ruby/1.9.1/fileutils.rb:1372:in `block (2 levels) in copy_file'
```

**Comment by mrdavidlaing** [comment]
Hmm.  The packer job that builds the bosh-lite image specifically runs a script (https://github.com/cloudfoundry/bosh-lite/blob/master/templates/virtualbox.json#L94) called
`scripts/set-temp-dir.sh`

Which is (https://github.com/cloudfoundry/bosh-lite/blob/master/scripts/set-temp-dir.sh) contains:
```
#!/bin/bash
(cat <<PROFILE
export TMPDIR=${HOME}/tmp
PROFILE
) >> $HOME/.profile
mkdir -p $HOME/tmp
```

It would appear that one’s shell in the logsearch workspace is ignoring .profile because it uses   `.bash_profile` to configure the shell environment 

So, a potential fix which is in keeping with the (wierd) way that the upstream bosh-lite is doing things, is to ensure that the logsearch workspaces’ `~/.bash_profile` sources `~/.profile`
